# Generated by Django 5.2.2 on 2025-06-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория номи')),
                ('slug', models.SlugField(help_text='URL uchun foydalaniladi', max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Яратилган сана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Янгиланган сана')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Маҳсулот номи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тавсиф')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нарx')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Расм')),
                ('slug', models.SlugField(help_text='URL uchun foydalaniladi', max_length=200, unique=True, verbose_name='Slug')),
                ('is_available', models.BooleanField(default=True, verbose_name='Мавjudлик')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Яратилган сана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Янгиланган сана')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Маҳсулот',
                'verbose_name_plural': 'Маҳсулотлар',
                'ordering': ['-created_at'],
            },
        ),
    ]
