# Generated by Django 5.2.2 on 2025-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='Админ ҳуқуқи'),
        ),
    ]
